language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
deploy:
  provider: surge
  skip_cleanup: true
  domain: colab.surge.sh
  project: ./src/build/
on:
  branch: master